-- Banner istituzionale EVERAS in coda agli ordini attivi (tracking views/click/CTR).
-- ID fisso così resta stabile tra ambienti e non viene duplicato.

insert into public.advertising_orders (
  id,
  package_id,
  package_name,
  placement,
  duration_months,
  price,
  list_price,
  promo_price,
  final_price,
  promo_applied,
  currency,
  status,
  company_name,
  contact_name,
  email,
  phone,
  address,
  postal_code,
  city,
  province,
  website_url,
  banner_url,
  banner_urls,
  admin_notes,
  submitted_at,
  paid_at,
  start_date,
  expiration_date,
  approved_at
)
values (
  'e7e8a500-0000-4000-8000-000000000001',
  'everas-self-promo',
  'EVERAS — Banner istituzionale',
  'home',
  12,
  0,
  0,
  null,
  0,
  false,
  'EUR',
  'active',
  'EVERAS',
  'EVERAS',
  'info@everas.it',
  '—',
  'Sardegna',
  '07100',
  'Sassari',
  'SS',
  'https://www.everas.it/pubblicita',
  '/images/ads/everas-advertise-promo.gif',
  array['/images/ads/everas-advertise-promo.gif'],
  'Banner istituzionale EVERAS (Special Prezzo Lancio). Usato per tracking views/click/CTR.',
  now(),
  now(),
  now(),
  '2099-12-31 23:59:59+00',
  now()
)
on conflict (id) do update set
  status = excluded.status,
  package_id = excluded.package_id,
  package_name = excluded.package_name,
  placement = excluded.placement,
  banner_url = excluded.banner_url,
  banner_urls = excluded.banner_urls,
  website_url = excluded.website_url,
  expiration_date = excluded.expiration_date,
  admin_notes = excluded.admin_notes;
