-- Banner partner Monstera e Zoe: stessi contatori views/click/CTR di EVERAS.

insert into public.advertising_orders (
  id,
  package_id,
  package_name,
  placement,
  duration_months,
  price,
  list_price,
  promo_price,
  final_price,
  promo_applied,
  currency,
  status,
  company_name,
  contact_name,
  email,
  phone,
  address,
  postal_code,
  city,
  province,
  website_url,
  banner_url,
  banner_urls,
  admin_notes,
  submitted_at,
  paid_at,
  start_date,
  expiration_date,
  approved_at
)
values
(
  'e7e8a500-0000-4000-8000-000000000002',
  'monstera-partner-promo',
  'Monstera — Banner partner',
  'home',
  12,
  0,
  0,
  null,
  0,
  false,
  'EUR',
  'active',
  'Monstera',
  'Monstera',
  'info@everas.it',
  '339 542 2343',
  'Via Predda Niedda 37/f',
  '07100',
  'Sassari',
  'SS',
  'https://www.google.com/maps/search/?api=1&query=Monstera%20Via%20Predda%20Niedda%2037f%20Sassari',
  '/images/monstera/monstera-stairs.gif',
  array['/images/monstera/monstera-stairs.gif'],
  'Banner partner Monstera. Tracking views/click/CTR.',
  now(),
  now(),
  now(),
  '2099-12-31 23:59:59+00',
  now()
),
(
  'e7e8a500-0000-4000-8000-000000000003',
  'zoe-partner-promo',
  'Zoe — Banner partner',
  'home',
  12,
  0,
  0,
  null,
  0,
  false,
  'EUR',
  'active',
  'Zoe',
  'Zoe Academy',
  'info@everas.it',
  '—',
  'Sassari',
  '07100',
  'Sassari',
  'SS',
  'https://www.facebook.com/Zoe.talenti.corsi.eventi.progetti',
  '/images/zoe/zoe-robot.gif',
  array['/images/zoe/zoe-robot.gif'],
  'Banner partner Zoe. Tracking views/click/CTR.',
  now(),
  now(),
  now(),
  '2099-12-31 23:59:59+00',
  now()
)
on conflict (id) do update set
  status = excluded.status,
  package_id = excluded.package_id,
  package_name = excluded.package_name,
  placement = excluded.placement,
  banner_url = excluded.banner_url,
  banner_urls = excluded.banner_urls,
  website_url = excluded.website_url,
  expiration_date = excluded.expiration_date,
  admin_notes = excluded.admin_notes,
  company_name = excluded.company_name;
